import Head from "next/head";
import Image from "next/image";
import { Button, Col, Container, Row } from "reactstrap";
import { BsFillCaretRightFill } from "react-icons/bs";
import Showcase from "../components/Showcase";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Digiart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container fluid="lg" className="">
          <Row className="d-flex align-items-center">
            <Col xs="12" sm="12" lg="5">
              <h1 className="font-weight-bold mb-3">
                Nous aidons les artistes à développer leur{" "}
                <span className="important-word">business...</span>
              </h1>
              <p className="secondary-text mb-5">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam
                et lacinia nunc, quis laoreet libero. Nullam ornare ut lorem
                vitae tincidunt. Nullam lacinia ut massa in venenatis. Phasellus
                vestibulum et sapien et gravida. Phasellus varius ac leo id
                ultricies. Nunc dapibus, eros nec gravida placerat, neque augue
                convallis tellus, id varius justo felis nec velit.
              </p>

              <Row>
                <Col>
                  <Button color="primary">Commencer à vendre</Button>
                </Col>
                <Col>
                  <Button color="primary" outline>
                    Consulter les oeuvres <BsFillCaretRightFill />
                  </Button>
                </Col>
              </Row>
            </Col>

            <Col className="d-none d-lg-block" lg="7">
              <Image
                src="/images/rocket.png"
                alt="Picture of a girl on a rocket"
                width={863}
                height={863}
              />
            </Col>
          </Row>
        </Container>

        <Showcase />
      </main>

      <div className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
}
